nome = str(input('Digite seu nome completo: ')).strip()
print(nome.upper())
print(nome.lower())
print(len(nome) - nome.count(' '))
#print(nome.find(' '))
separa = nome.split()
print(separa[0], len(separa[0]))
